Create events for data
marshmallow-insurance/uk-multi-ab-testing pull request #4
Opened 2023-11-07 15:27 UTC by SvenStrFinlay

2023-11-07 18:00 UTC, jjlharrison approved these changes

2023-11-08 08:47 UTC, elkkhan requested changes

2023-11-08 08:47 UTC, elkkhan commented on terraform/event_sourcing.tf
> +        { name = "PARTICIPANT_VERSION", type = "INTEGER", nullable = false },
do we want to have a TEST_VERSION too?

2023-11-08 09:43 UTC, SvenStrFinlay commented on terraform/event_sourcing.tf
> +        { name = "PARTICIPANT_VERSION", type = "INTEGER", nullable = false },
Tis in the data object

2023-11-08 10:28 UTC, elkkhan approved these changes

2023-11-08 10:28 UTC, merged